import React from 'react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react'
import {AppHeader,PageLink,usePage} from './AppNavigation.jsx'
function Harness(){const {path,navigate,heading}=usePage();return <><AppHeader path={path} navigate={navigate}/><h1 ref={heading} tabIndex={-1}>{path}</h1><PageLink to="/missing" navigate={navigate}>Unknown route</PageLink></>}
beforeEach(()=>{window.history.replaceState(null,'','/');vi.spyOn(window,'scrollTo').mockImplementation(()=>{})})
afterEach(()=>{cleanup();vi.restoreAllMocks()})
it('five routes have real URLs and exact active navigation',()=>{render(<Harness/>);expect(screen.getByRole('navigation',{name:'Main navigation'}).querySelectorAll('a')).toHaveLength(5);fireEvent.click(screen.getByRole('link',{name:'Weather & AI',exact:true}));expect(window.location.pathname).toBe('/weather');expect(screen.getByRole('link',{name:'Weather & AI',exact:true}).getAttribute('aria-current')).toBe('page');expect(screen.getByRole('link',{name:'Home',exact:true}).getAttribute('aria-current')).toBeNull();expect(document.title).toBe('Weather & AI · FloodPulse');expect(document.activeElement).toBe(screen.getByRole('heading'))})
it('direct trailing-slash URLs and browser popstate restore the page',()=>{window.history.replaceState(null,'','/shelters/');render(<Harness/>);expect(screen.getByRole('link',{name:'Shelters',exact:true}).getAttribute('aria-current')).toBe('page');act(()=>{window.history.replaceState(null,'','/flood-map');window.dispatchEvent(new PopStateEvent('popstate'))});expect(screen.getByRole('heading').textContent).toBe('/flood-map')})
it('mobile menu closes on navigation and Escape returns focus',()=>{render(<Harness/>);const open=()=>fireEvent.click(screen.getByRole('button',{name:'Open navigation menu'}));open();expect(screen.getByRole('button',{name:'Close navigation menu'}).getAttribute('aria-expanded')).toBe('true');fireEvent.keyDown(screen.getByRole('navigation'),{key:'Escape'});expect(document.activeElement).toBe(screen.getByRole('button',{name:'Open navigation menu'}));open();fireEvent.click(screen.getByRole('link',{name:'Admin',exact:true}));expect(screen.getByRole('button',{name:'Open navigation menu'}).getAttribute('aria-expanded')).toBe('false')})
it('modified clicks retain native new-tab behavior',()=>{const navigate=vi.fn();render(<PageLink to="/weather" navigate={navigate}>Weather</PageLink>);fireEvent.click(screen.getByRole('link'),{ctrlKey:true});expect(navigate).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('link'));expect(navigate).toHaveBeenCalledWith('/weather')})
it('unknown paths have no fabricated active page',()=>{window.history.replaceState(null,'','/missing');render(<Harness/>);expect(document.title).toBe('Page unavailable · FloodPulse');expect(screen.getByRole('navigation').querySelector('[aria-current]')).toBeNull()})
