import React from 'react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {readFileSync} from 'node:fs'
import FloodIntelligenceMap from './FloodIntelligenceMap.jsx'
const directory=JSON.parse(readFileSync('../data/reference/karnataka_location_directory_v2/directory.json','utf8'))
const mock=vi.hoisted(()=>({map:vi.fn(),tileLayer:vi.fn(),geoJSON:vi.fn(),circleMarker:vi.fn(),clicks:[]}))
vi.mock('leaflet',()=>({default:mock}))
vi.mock('./DrainageResearchLayers.jsx',()=>({default:()=> <div>Existing drainage rasters remain separate</div>}))
const props={event_id:2728,grid_row:1,grid_col:2,district:'Udupi',clear_views:2,start_date:'2005-09-14',end_date_inclusive:'2005-09-30',place_name:null,mechanism:{method:'No reviewed source establishes a flood mechanism'},geometry_meaning:'Source-exported observation-qualified raster cell',processing_grid_m:250,observation_quality:'qualified_source_mask_and_clear_views',source:{name:'Global Flood Database V1',url:'https://developers.google.com/earth-engine/datasets/catalog/GLOBAL_FLOOD_DB_MODIS_EVENTS_V1',license:'CC BY-NC 4.0',license_url:'https://creativecommons.org/licenses/by-nc/4.0/',conditions:'Attribution and non-commercial use required'},dataset_version:'udupi_flood_spatial_v1',image_id:'GLOBAL_FLOOD_DB/MODIS_EVENTS/V1/DFO_2728',retrieved_at:'2026-10-03T00:00:00Z',limitations:'Historical maximum, not daily occurrence',source_geometry_sha256:'a'.repeat(64)}
const feature={type:'Feature',id:'gfd:2728:r1:c2',properties:props,geometry:{type:'Polygon',coordinates:[[[74,13],[75,13],[75,14],[74,13]]]}}
const history={status:'available',geojson:{type:'FeatureCollection',features:[feature]},events:[{event_id:2728,qualified_pixel_count:1,image_id:props.image_id,start_date:props.start_date,end_date_inclusive:props.end_date_inclusive}],total:1,coverage:{historical_events:1},boundary:null}
const reply=(data,ok=true)=>Promise.resolve({ok,json:async()=>data})
function responses(url){
 const u=new URL(url,'http://localhost')
 if(u.pathname==='/api/flood-map/districts')return reply({status:'available',items:directory.districts,total:31})
 if(u.pathname==='/api/flood-map/historical')return reply(u.searchParams.has('district_id')&&u.searchParams.get('district_id')!=='nic:udupi.nic.in'?{...history,events:[],geojson:{type:'FeatureCollection',features:[]},total:0,coverage:{historical_events:0}}:history)
 if(u.pathname==='/api/flood-map/hazards')return reply({status:'unavailable',message:'No verified potential flood-prone zone dataset is available for this district.',geojson:{type:'FeatureCollection',features:[]}})
 if(u.pathname==='/api/flood-map/drainage')return reply({status:'unavailable',message:'No reviewed drainage context is available for this district.'})
 if(u.pathname.startsWith('/api/flood-map/features/'))return reply({feature})
 if(u.pathname==='/api/shelters')return reply({status:'available',mode:'live',shelters:[]})
 throw Error('Unexpected test request '+url)
}
beforeEach(()=>{
 vi.clearAllMocks();mock.clicks.length=0
 mock.map.mockReturnValue({setView:vi.fn().mockReturnThis(),on:vi.fn(),fitBounds:vi.fn(),removeLayer:vi.fn(),remove:vi.fn()})
 mock.tileLayer.mockReturnValue({addTo:vi.fn().mockReturnThis(),on:vi.fn()})
 mock.circleMarker.mockReturnValue({addTo:vi.fn().mockReturnThis(),bindPopup:vi.fn()})
 mock.geoJSON.mockImplementation((data,options)=>{for(const f of data.features||[])options?.onEachFeature?.(f,{bindTooltip:vi.fn(),on:(name,fn)=>mock.clicks.push(fn)});return {addTo:vi.fn().mockReturnThis(),getBounds:()=>({})}})
 vi.stubGlobal('fetch',vi.fn(responses))
})
afterEach(()=>{cleanup();vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks()})
const start=async()=>{render(<FloodIntelligenceMap/>);await screen.findByText(/1 eligible historical cells/);await waitFor(()=>expect(mock.geoJSON.mock.calls.some(([d])=>JSON.stringify(d)===JSON.stringify(history.geojson))).toBe(true))}
it('all 31 genuine district names have stable NIC identifiers',async()=>{await start();const select=screen.getByLabelText('Flood Map district');expect(select.options.length).toBe(32);for(const d of directory.districts)expect([...select.options].some(o=>o.value===d.id&&o.text===d.name)).toBe(true)})
it('district filtering and statewide reset preserve layer choices',async()=>{await start();fireEvent.click(screen.getByLabelText('Potential Flood-Prone Zones'));fireEvent.change(screen.getByLabelText('Flood Map district'),{target:{value:'nic:kolar.nic.in'}});await screen.findByText(/0 eligible historical cells/);expect(screen.getByText(/Verified public navigation bounds are unavailable/)).toBeTruthy();expect(screen.getByLabelText('Potential Flood-Prone Zones').checked).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Return to statewide view'}));await screen.findByText(/1 eligible historical cells/);expect(fetch.mock.calls.some(([u])=>u.includes('district_id=nic%3Akolar.nic.in'))).toBe(true)})
it('uses permitted navigation bounds and invents no unavailable bounds',async()=>{await start();const map=mock.map.mock.results[0].value;fireEvent.change(screen.getByLabelText('Flood Map district'),{target:{value:'nic:udupi.nic.in'}});await waitFor(()=>expect(map.fitBounds).toHaveBeenCalledWith(directory.districts.find(d=>d.id==='nic:udupi.nic.in').navigation_bounds,expect.any(Object)));map.fitBounds.mockClear();fireEvent.change(screen.getByLabelText('Flood Map district'),{target:{value:'nic:kolar.nic.in'}});await screen.findByText(/0 eligible/);expect(map.fitBounds).not.toHaveBeenCalled()})
it('passes original polygons to Leaflet instead of fabricated event points',async()=>{await start();expect(mock.geoJSON.mock.calls.some(([d])=>JSON.stringify(d)===JSON.stringify(history.geojson))).toBe(true);expect(mock.circleMarker).not.toHaveBeenCalled()})
it('historical and potential layers are independently controlled',async()=>{await start();fireEvent.click(screen.getByLabelText('Potential Flood-Prone Zones'));await screen.findByText(/No verified potential/);expect(screen.getByLabelText('Historical Flood Locations').checked).toBe(true);fireEvent.click(screen.getByLabelText('Historical Flood Locations'));await screen.findByText('Historical layer hidden.');expect(screen.queryByLabelText('Historical evidence cell (keyboard alternative)')).toBeNull();expect(screen.getByLabelText('Potential Flood-Prone Zones').checked).toBe(true)})
it('keyboard selection opens unknown-mechanism source details and closes',async()=>{await start();fireEvent.change(screen.getByLabelText('Historical evidence cell (keyboard alternative)'),{target:{value:feature.id}});await screen.findByRole('heading',{name:'Flood evidence details'});expect(screen.getByText(/Unknown — No reviewed source/)).toBeTruthy();expect(screen.getByText('No verified settlement name for this raster cell')).toBeTruthy();expect(screen.getByText(props.source_geometry_sha256)).toBeTruthy();expect(screen.getByText('Not validated')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Close details'}));expect(screen.queryByRole('heading',{name:'Flood evidence details'})).toBeNull()})
it('polygon click opens details without changing weather point',async()=>{const onPoint=vi.fn();render(<FloodIntelligenceMap onPoint={onPoint}/>);await screen.findByText(/1 eligible/);await waitFor(()=>expect(mock.clicks[0]).toBeTypeOf("function"));act(()=>mock.clicks[0]());await screen.findByRole('heading',{name:'Flood evidence details'});expect(onPoint).not.toHaveBeenCalled()})
it('drainage no-data is context rather than hazard classification',async()=>{await start();fireEvent.click(screen.getByLabelText('Drainage / waterways'));await screen.findByRole('heading',{name:'Drainage context'});expect(screen.getByText(/overflow risk not established/)).toBeTruthy();expect(screen.getByText(/Absence of mapped data/)).toBeTruthy()})
it('shelter toggle shows genuine empty state with no fabricated points',async()=>{await start();fireEvent.click(screen.getByLabelText('Verified shelters'));await screen.findByText(/No currently verified open shelters/);expect(mock.circleMarker).not.toHaveBeenCalled()})
it('rejects unverified closed shelter responses',async()=>{fetch.mockImplementation(u=>u==='/api/shelters'?reply({mode:'live',shelters:[{status:'closed',latitude:13,longitude:74}]}):responses(u));await start();fireEvent.click(screen.getByLabelText('Verified shelters'));await screen.findByText(/Shelter availability could not be verified/);expect(mock.circleMarker).not.toHaveBeenCalled()})
it('provider errors show retry without replacement polygons',async()=>{fetch.mockImplementation(u=>u.startsWith('/api/flood-map/historical')?reply({detail:'Historical checksum failed'},false):responses(u));render(<FloodIntelligenceMap/>);await screen.findByRole('alert');expect(screen.getByText(/No substitute geometry/)).toBeTruthy();expect(mock.geoJSON).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Retry map evidence'})).toBeTruthy()})
it('late previous-district response cannot replace current filtering',async()=>{let release;fetch.mockImplementation(u=>u.includes('district_id=nic%3Audupi.nic.in')?new Promise(r=>{release=()=>r({ok:true,json:async()=>history})}):responses(u));await start();fireEvent.change(screen.getByLabelText('Flood Map district'),{target:{value:'nic:udupi.nic.in'}});fireEvent.change(screen.getByLabelText('Flood Map district'),{target:{value:'nic:kolar.nic.in'}});await screen.findByText(/0 eligible/);await act(async()=>release());expect(screen.queryByText(/1 eligible/)).toBeNull()})
it('request controllers are cleaned up on unmount',()=>{const signals=[];fetch.mockImplementation((u,options)=>{signals.push(options.signal);return new Promise(()=>{})});const {unmount}=render(<FloodIntelligenceMap/>);unmount();expect(signals.length).toBe(2);expect(signals.every(s=>s.aborted)).toBe(true)})
it('request timeout is explicit',async()=>{vi.useFakeTimers();fetch.mockImplementation((u,{signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')))));render(<FloodIntelligenceMap/>);await act(async()=>{await vi.advanceTimersByTimeAsync(15000)});expect(screen.getByRole('alert').textContent).toContain('timed out')})
