"""phase_2_2_data_contract

Revision ID: 7eee813798dd
Revises: 
Create Date: 2026-09-17 17:33:25.697654
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
import geoalchemy2

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eee813798dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('access_method', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('geographic_coverage', sa.String(length=100), nullable=True),
    sa.Column('update_frequency', sa.String(length=50), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ml_dataset_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_snapshot', sa.Text(), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=50), nullable=True),
    sa.Column('training_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('label_definition', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('river_basins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_river_basins_geometry', 'river_basins', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('states',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_states_geometry', 'states', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'USER'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('USER', 'ADMIN')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('community_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_flood_depth', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('image_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'SUBMITTED'"), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED')", name='ck_community_report_status'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)', name='ck_community_report_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)', name='ck_community_report_longitude'),
    sa.CheckConstraint('reported_flood_depth IS NULL OR reported_flood_depth >= 0.0', name='ck_community_report_depth'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_reports_geometry', 'community_reports', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_community_reports_reported_at', 'community_reports', ['reported_at'], unique=False)
    op.create_index('ix_community_reports_status', 'community_reports', ['status'], unique=False)
    op.create_index('ix_community_reports_user_id', 'community_reports', ['user_id'], unique=False)
    op.create_table('data_ingestion_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_rejected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED')", name='ck_ingestion_run_status'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_source_id', 'data_ingestion_runs', ['source_id'], unique=False)
    op.create_index('ix_ingestion_runs_started_at', 'data_ingestion_runs', ['started_at'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_districts_centroid', 'districts', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index('idx_districts_geometry', 'districts', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_districts_state_id', 'districts', ['state_id'], unique=False)
    op.create_table('flood_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('affected_area', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.CheckConstraint('affected_area IS NULL OR affected_area >= 0.0', name='ck_flood_event_affected_area'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_flood_event_confidence'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flood_events_geometry', 'flood_events', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_flood_events_source_id', 'flood_events', ['source_id'], unique=False)
    op.create_index('ix_flood_events_start_time', 'flood_events', ['start_time'], unique=False)
    op.create_table('flood_hazard_zones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('hazard_class', sa.String(length=50), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flood_hazard_geometry', 'flood_hazard_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_flood_hazard_source_id', 'flood_hazard_zones', ['source_id'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('training_dataset_version', sa.UUID(), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=50), nullable=True),
    sa.Column('target_definition', sa.Text(), nullable=True),
    sa.Column('training_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['training_dataset_version'], ['ml_dataset_versions.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_ml_models_dataset_version', 'ml_models', ['training_dataset_version'], unique=False)
    op.create_table('sub_basins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('basin_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['basin_id'], ['river_basins.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_sub_basins_geometry', 'sub_basins', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_sub_basins_basin_id', 'sub_basins', ['basin_id'], unique=False)
    op.create_table('terrain_datasets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('coverage', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_terrain_datasets_coverage', 'terrain_datasets', ['coverage'], unique=False, postgresql_using='gist')
    op.create_index('ix_terrain_datasets_source_id', 'terrain_datasets', ['source_id'], unique=False)
    op.create_table('land_covers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('class_code', sa.String(length=50), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('observation_year', sa.Integer(), nullable=True),
    sa.CheckConstraint('observation_year IS NULL OR (observation_year >= 1900 AND observation_year <= 2100)', name='ck_land_covers_observation_year'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_land_covers_geometry', 'land_covers', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_land_covers_district_id', 'land_covers', ['district_id'], unique=False)
    op.create_index('ix_land_covers_source_id', 'land_covers', ['source_id'], unique=False)
    op.create_table('rainfall_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('station_id', sa.String(length=100), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("quality_status IS NULL OR quality_status IN ('VALID', 'SUSPECT', 'INVALID', 'MISSING', 'STALE')", name='ck_rainfall_obs_quality_status'),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name='ck_rainfall_obs_duration'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)', name='ck_rainfall_obs_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)', name='ck_rainfall_obs_longitude'),
    sa.CheckConstraint('rainfall_mm IS NULL OR rainfall_mm >= 0.0', name='ck_rainfall_obs_rainfall_mm'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rainfall_obs_geometry', 'rainfall_observations', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_rainfall_obs_district_observed', 'rainfall_observations', ['district_id', 'observed_at'], unique=False)
    op.create_index('ix_rainfall_obs_source_id', 'rainfall_observations', ['source_id'], unique=False)
    op.create_index('ix_rainfall_obs_source_record', 'rainfall_observations', ['source_id', 'source_record_id'], unique=False)
    op.create_table('rivers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('basin_id', sa.UUID(), nullable=True),
    sa.Column('sub_basin_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['basin_id'], ['river_basins.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['sub_basin_id'], ['sub_basins.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rivers_geometry', 'rivers', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_rivers_basin_id', 'rivers', ['basin_id'], unique=False)
    op.create_index('ix_rivers_sub_basin_id', 'rivers', ['sub_basin_id'], unique=False)
    op.create_table('taluks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_taluks_geometry', 'taluks', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_taluks_district_id', 'taluks', ['district_id'], unique=False)
    op.create_table('water_bodies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('waterbody_type', sa.String(length=50), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_water_bodies_geometry', 'water_bodies', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_water_bodies_district_id', 'water_bodies', ['district_id'], unique=False)
    op.create_index('ix_water_bodies_source_id', 'water_bodies', ['source_id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('location_reference', sa.String(length=100), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('rainfall_probability', sa.Float(), nullable=True),
    sa.Column('forecast_rainfall_mm', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("quality_status IS NULL OR quality_status IN ('VALID', 'SUSPECT', 'INVALID', 'MISSING', 'STALE')", name='ck_weather_fcst_quality_status'),
    sa.CheckConstraint('forecast_rainfall_mm IS NULL OR forecast_rainfall_mm >= 0.0', name='ck_weather_fcst_rainfall_mm'),
    sa.CheckConstraint('humidity IS NULL OR (humidity >= 0.0 AND humidity <= 100.0)', name='ck_weather_fcst_humidity'),
    sa.CheckConstraint('rainfall_probability IS NULL OR (rainfall_probability >= 0.0 AND rainfall_probability <= 1.0)', name='ck_weather_fcst_rainfall_prob'),
    sa.CheckConstraint('wind_speed IS NULL OR wind_speed >= 0.0', name='ck_weather_fcst_wind_speed'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_fcst_district_for', 'weather_forecasts', ['district_id', 'forecast_for'], unique=False)
    op.create_index('ix_weather_fcst_source_id', 'weather_forecasts', ['source_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('location_reference', sa.String(length=100), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("quality_status IS NULL OR quality_status IN ('VALID', 'SUSPECT', 'INVALID', 'MISSING', 'STALE')", name='ck_weather_obs_quality_status'),
    sa.CheckConstraint('humidity IS NULL OR (humidity >= 0.0 AND humidity <= 100.0)', name='ck_weather_obs_humidity'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)', name='ck_weather_obs_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)', name='ck_weather_obs_longitude'),
    sa.CheckConstraint('wind_direction IS NULL OR (wind_direction >= 0.0 AND wind_direction <= 360.0)', name='ck_weather_obs_wind_direction'),
    sa.CheckConstraint('wind_speed IS NULL OR wind_speed >= 0.0', name='ck_weather_obs_wind_speed'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weather_obs_geometry', 'weather_observations', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_weather_obs_district_observed', 'weather_observations', ['district_id', 'observed_at'], unique=False)
    op.create_index('ix_weather_obs_source_id', 'weather_observations', ['source_id'], unique=False)
    op.create_index('ix_weather_obs_source_record', 'weather_observations', ['source_id', 'source_record_id'], unique=False)
    op.create_table('emergency_facilities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('taluk_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("facility_type IN ('HOSPITAL', 'POLICE_STATION', 'FIRE_STATION', 'RELIEF_CENTRE', 'EVACUATION_CENTRE')", name='ck_emergency_facility_type'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)', name='ck_emergency_facility_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)', name='ck_emergency_facility_longitude'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['taluk_id'], ['taluks.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emergency_fac_geometry', 'emergency_facilities', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_emergency_fac_district_id', 'emergency_facilities', ['district_id'], unique=False)
    op.create_index('ix_emergency_fac_source_id', 'emergency_facilities', ['source_id'], unique=False)
    op.create_index('ix_emergency_fac_taluk_id', 'emergency_facilities', ['taluk_id'], unique=False)
    op.create_index('ix_emergency_fac_type', 'emergency_facilities', ['facility_type'], unique=False)
    op.create_table('flood_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('observation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('flooded', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('flood_depth', sa.Float(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('taluk_id', sa.UUID(), nullable=True),
    sa.Column('basin_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("quality_status IS NULL OR quality_status IN ('VALID', 'SUSPECT', 'INVALID', 'MISSING', 'STALE')", name='ck_flood_obs_quality_status'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_flood_obs_confidence'),
    sa.CheckConstraint('flood_depth IS NULL OR flood_depth >= 0.0', name='ck_flood_obs_depth'),
    sa.ForeignKeyConstraint(['basin_id'], ['river_basins.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['taluk_id'], ['taluks.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flood_obs_geometry', 'flood_observations', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_flood_obs_basin_id', 'flood_observations', ['basin_id'], unique=False)
    op.create_index('ix_flood_obs_district_id', 'flood_observations', ['district_id'], unique=False)
    op.create_index('ix_flood_obs_observation_time', 'flood_observations', ['observation_time'], unique=False)
    op.create_index('ix_flood_obs_source_id', 'flood_observations', ['source_id'], unique=False)
    op.create_index('ix_flood_obs_source_record', 'flood_observations', ['source_id', 'source_record_id'], unique=False)
    op.create_index('ix_flood_obs_taluk_id', 'flood_observations', ['taluk_id'], unique=False)
    op.create_table('localities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('taluk_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)', name='ck_localities_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)', name='ck_localities_longitude'),
    sa.ForeignKeyConstraint(['taluk_id'], ['taluks.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_localities_centroid', 'localities', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index('idx_localities_geometry', 'localities', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_localities_taluk_id', 'localities', ['taluk_id'], unique=False)
    op.create_table('prediction_grid_cells',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('taluk_id', sa.UUID(), nullable=True),
    sa.Column('basin_id', sa.UUID(), nullable=True),
    sa.Column('sub_basin_id', sa.UUID(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('distance_to_river', sa.Float(), nullable=True),
    sa.Column('distance_to_waterbody', sa.Float(), nullable=True),
    sa.CheckConstraint('distance_to_river IS NULL OR distance_to_river >= 0.0', name='ck_pred_grid_dist_river'),
    sa.CheckConstraint('distance_to_waterbody IS NULL OR distance_to_waterbody >= 0.0', name='ck_pred_grid_dist_waterbody'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)', name='ck_pred_grid_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)', name='ck_pred_grid_longitude'),
    sa.CheckConstraint('slope IS NULL OR slope >= 0.0', name='ck_pred_grid_slope'),
    sa.ForeignKeyConstraint(['basin_id'], ['river_basins.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['sub_basin_id'], ['sub_basins.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['taluk_id'], ['taluks.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pred_grid_geometry', 'prediction_grid_cells', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_pred_grid_basin_id', 'prediction_grid_cells', ['basin_id'], unique=False)
    op.create_index('ix_pred_grid_district_id', 'prediction_grid_cells', ['district_id'], unique=False)
    op.create_index('ix_pred_grid_taluk_id', 'prediction_grid_cells', ['taluk_id'], unique=False)
    op.create_table('reservoirs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('river_id', sa.UUID(), nullable=True),
    sa.Column('basin_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('full_reservoir_level', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)', name='ck_reservoirs_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)', name='ck_reservoirs_longitude'),
    sa.ForeignKeyConstraint(['basin_id'], ['river_basins.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['river_id'], ['rivers.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_reservoirs_geometry', 'reservoirs', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_reservoirs_basin_id', 'reservoirs', ['basin_id'], unique=False)
    op.create_index('ix_reservoirs_district_id', 'reservoirs', ['district_id'], unique=False)
    op.create_index('ix_reservoirs_river_id', 'reservoirs', ['river_id'], unique=False)
    op.create_index('ix_reservoirs_source_id', 'reservoirs', ['source_id'], unique=False)
    op.create_table('river_stations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('river_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('station_code', sa.String(length=50), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('warning_level', sa.Float(), nullable=True),
    sa.Column('danger_level', sa.Float(), nullable=True),
    sa.Column('highest_flood_level', sa.Float(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)', name='ck_river_stations_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)', name='ck_river_stations_longitude'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['river_id'], ['rivers.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_code')
    )
    op.create_index('idx_river_stations_geometry', 'river_stations', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_river_stations_district_id', 'river_stations', ['district_id'], unique=False)
    op.create_index('ix_river_stations_river_id', 'river_stations', ['river_id'], unique=False)
    op.create_index('ix_river_stations_source_id', 'river_stations', ['source_id'], unique=False)
    op.create_table('telegram_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('taluk_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['taluk_id'], ['taluks.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index('ix_telegram_sub_district_id', 'telegram_subscriptions', ['district_id'], unique=False)
    op.create_index('ix_telegram_sub_taluk_id', 'telegram_subscriptions', ['taluk_id'], unique=False)
    op.create_index('ix_telegram_sub_user_id', 'telegram_subscriptions', ['user_id'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grid_cell_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rainfall_1h', sa.Float(), nullable=True),
    sa.Column('rainfall_3h', sa.Float(), nullable=True),
    sa.Column('rainfall_6h', sa.Float(), nullable=True),
    sa.Column('rainfall_12h', sa.Float(), nullable=True),
    sa.Column('rainfall_24h', sa.Float(), nullable=True),
    sa.Column('forecast_rainfall', sa.Float(), nullable=True),
    sa.Column('river_level', sa.Float(), nullable=True),
    sa.Column('river_trend', sa.String(length=20), nullable=True),
    sa.Column('reservoir_level', sa.Float(), nullable=True),
    sa.Column('reservoir_inflow', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('distance_to_river', sa.Float(), nullable=True),
    sa.Column('landcover_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waterlogging_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flood_hazard_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['ml_dataset_versions.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['prediction_grid_cells.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feat_snap_cell_time', 'feature_snapshots', ['grid_cell_id', 'timestamp'], unique=False)
    op.create_index('ix_feat_snap_dataset_version', 'feature_snapshots', ['dataset_version_id'], unique=False)
    op.create_table('flood_predictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grid_cell_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('prediction_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prediction_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flood_probability', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('top_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IS NULL OR risk_level IN ('LOW', 'MODERATE', 'HIGH', 'SEVERE')", name='ck_flood_pred_risk_level'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_flood_pred_confidence'),
    sa.CheckConstraint('flood_probability IS NULL OR (flood_probability >= 0.0 AND flood_probability <= 1.0)', name='ck_flood_pred_probability'),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['prediction_grid_cells.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flood_pred_cell_for', 'flood_predictions', ['grid_cell_id', 'prediction_for'], unique=False)
    op.create_index('ix_flood_pred_created_at', 'flood_predictions', ['created_at'], unique=False)
    op.create_index('ix_flood_pred_model_id', 'flood_predictions', ['model_id'], unique=False)
    op.create_table('reservoir_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reservoir_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('water_level', sa.Float(), nullable=True),
    sa.Column('storage', sa.Float(), nullable=True),
    sa.Column('storage_percentage', sa.Float(), nullable=True),
    sa.Column('inflow', sa.Float(), nullable=True),
    sa.Column('outflow', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("quality_status IS NULL OR quality_status IN ('VALID', 'SUSPECT', 'INVALID', 'MISSING', 'STALE')", name='ck_reservoir_obs_quality_status'),
    sa.CheckConstraint('storage_percentage IS NULL OR (storage_percentage >= 0.0 AND storage_percentage <= 100.0)', name='ck_reservoir_obs_storage_percentage'),
    sa.ForeignKeyConstraint(['reservoir_id'], ['reservoirs.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservoir_obs_reservoir_observed', 'reservoir_observations', ['reservoir_id', 'observed_at'], unique=False)
    op.create_index('ix_reservoir_obs_source_id', 'reservoir_observations', ['source_id'], unique=False)
    op.create_index('ix_reservoir_obs_source_record', 'reservoir_observations', ['source_id', 'source_record_id'], unique=False)
    op.create_table('river_forecasts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_water_level', sa.Float(), nullable=True),
    sa.Column('forecast_discharge', sa.Float(), nullable=True),
    sa.Column('forecast_status', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("quality_status IS NULL OR quality_status IN ('VALID', 'SUSPECT', 'INVALID', 'MISSING', 'STALE')", name='ck_river_fcst_quality_status'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['station_id'], ['river_stations.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_river_fcst_source_id', 'river_forecasts', ['source_id'], unique=False)
    op.create_index('ix_river_fcst_station_for', 'river_forecasts', ['station_id', 'forecast_for'], unique=False)
    op.create_table('river_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('water_level', sa.Float(), nullable=True),
    sa.Column('water_level_unit', sa.String(length=10), nullable=True),
    sa.Column('discharge', sa.Float(), nullable=True),
    sa.Column('discharge_unit', sa.String(length=10), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('warning_level', sa.Float(), nullable=True),
    sa.Column('danger_level', sa.Float(), nullable=True),
    sa.Column('highest_flood_level', sa.Float(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("quality_status IS NULL OR quality_status IN ('VALID', 'SUSPECT', 'INVALID', 'MISSING', 'STALE')", name='ck_river_obs_quality_status'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['station_id'], ['river_stations.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_river_obs_source_id', 'river_observations', ['source_id'], unique=False)
    op.create_index('ix_river_obs_source_record', 'river_observations', ['source_id', 'source_record_id'], unique=False)
    op.create_index('ix_river_obs_station_observed', 'river_observations', ['station_id', 'observed_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("source_type IN ('OFFICIAL_WARNING', 'AI_PREDICTION', 'ADMIN_ALERT')", name='ck_alert_source_type'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['prediction_id'], ['flood_predictions.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_geometry', 'alerts', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_district_id', 'alerts', ['district_id'], unique=False)
    op.create_index('ix_alerts_prediction_id', 'alerts', ['prediction_id'], unique=False)
    op.create_index('ix_alerts_source_type', 'alerts', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_source_type', table_name='alerts')
    op.drop_index('ix_alerts_prediction_id', table_name='alerts')
    op.drop_index('ix_alerts_district_id', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_index('idx_alerts_geometry', table_name='alerts', postgresql_using='gist')
    op.drop_table('alerts')
    op.drop_index('ix_river_obs_station_observed', table_name='river_observations')
    op.drop_index('ix_river_obs_source_record', table_name='river_observations')
    op.drop_index('ix_river_obs_source_id', table_name='river_observations')
    op.drop_table('river_observations')
    op.drop_index('ix_river_fcst_station_for', table_name='river_forecasts')
    op.drop_index('ix_river_fcst_source_id', table_name='river_forecasts')
    op.drop_table('river_forecasts')
    op.drop_index('ix_reservoir_obs_source_record', table_name='reservoir_observations')
    op.drop_index('ix_reservoir_obs_source_id', table_name='reservoir_observations')
    op.drop_index('ix_reservoir_obs_reservoir_observed', table_name='reservoir_observations')
    op.drop_table('reservoir_observations')
    op.drop_index('ix_flood_pred_model_id', table_name='flood_predictions')
    op.drop_index('ix_flood_pred_created_at', table_name='flood_predictions')
    op.drop_index('ix_flood_pred_cell_for', table_name='flood_predictions')
    op.drop_table('flood_predictions')
    op.drop_index('ix_feat_snap_dataset_version', table_name='feature_snapshots')
    op.drop_index('ix_feat_snap_cell_time', table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index('ix_telegram_sub_user_id', table_name='telegram_subscriptions')
    op.drop_index('ix_telegram_sub_taluk_id', table_name='telegram_subscriptions')
    op.drop_index('ix_telegram_sub_district_id', table_name='telegram_subscriptions')
    op.drop_table('telegram_subscriptions')
    op.drop_index('ix_river_stations_source_id', table_name='river_stations')
    op.drop_index('ix_river_stations_river_id', table_name='river_stations')
    op.drop_index('ix_river_stations_district_id', table_name='river_stations')
    op.drop_index('idx_river_stations_geometry', table_name='river_stations', postgresql_using='gist')
    op.drop_table('river_stations')
    op.drop_index('ix_reservoirs_source_id', table_name='reservoirs')
    op.drop_index('ix_reservoirs_river_id', table_name='reservoirs')
    op.drop_index('ix_reservoirs_district_id', table_name='reservoirs')
    op.drop_index('ix_reservoirs_basin_id', table_name='reservoirs')
    op.drop_index('idx_reservoirs_geometry', table_name='reservoirs', postgresql_using='gist')
    op.drop_table('reservoirs')
    op.drop_index('ix_pred_grid_taluk_id', table_name='prediction_grid_cells')
    op.drop_index('ix_pred_grid_district_id', table_name='prediction_grid_cells')
    op.drop_index('ix_pred_grid_basin_id', table_name='prediction_grid_cells')
    op.drop_index('idx_pred_grid_geometry', table_name='prediction_grid_cells', postgresql_using='gist')
    op.drop_table('prediction_grid_cells')
    op.drop_index('ix_localities_taluk_id', table_name='localities')
    op.drop_index('idx_localities_geometry', table_name='localities', postgresql_using='gist')
    op.drop_index('idx_localities_centroid', table_name='localities', postgresql_using='gist')
    op.drop_table('localities')
    op.drop_index('ix_flood_obs_taluk_id', table_name='flood_observations')
    op.drop_index('ix_flood_obs_source_record', table_name='flood_observations')
    op.drop_index('ix_flood_obs_source_id', table_name='flood_observations')
    op.drop_index('ix_flood_obs_observation_time', table_name='flood_observations')
    op.drop_index('ix_flood_obs_district_id', table_name='flood_observations')
    op.drop_index('ix_flood_obs_basin_id', table_name='flood_observations')
    op.drop_index('idx_flood_obs_geometry', table_name='flood_observations', postgresql_using='gist')
    op.drop_table('flood_observations')
    op.drop_index('ix_emergency_fac_type', table_name='emergency_facilities')
    op.drop_index('ix_emergency_fac_taluk_id', table_name='emergency_facilities')
    op.drop_index('ix_emergency_fac_source_id', table_name='emergency_facilities')
    op.drop_index('ix_emergency_fac_district_id', table_name='emergency_facilities')
    op.drop_index('idx_emergency_fac_geometry', table_name='emergency_facilities', postgresql_using='gist')
    op.drop_table('emergency_facilities')
    op.drop_index('ix_weather_obs_source_record', table_name='weather_observations')
    op.drop_index('ix_weather_obs_source_id', table_name='weather_observations')
    op.drop_index('ix_weather_obs_district_observed', table_name='weather_observations')
    op.drop_index('idx_weather_obs_geometry', table_name='weather_observations', postgresql_using='gist')
    op.drop_table('weather_observations')
    op.drop_index('ix_weather_fcst_source_id', table_name='weather_forecasts')
    op.drop_index('ix_weather_fcst_district_for', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index('ix_water_bodies_source_id', table_name='water_bodies')
    op.drop_index('ix_water_bodies_district_id', table_name='water_bodies')
    op.drop_index('idx_water_bodies_geometry', table_name='water_bodies', postgresql_using='gist')
    op.drop_table('water_bodies')
    op.drop_index('ix_taluks_district_id', table_name='taluks')
    op.drop_index('idx_taluks_geometry', table_name='taluks', postgresql_using='gist')
    op.drop_table('taluks')
    op.drop_index('ix_rivers_sub_basin_id', table_name='rivers')
    op.drop_index('ix_rivers_basin_id', table_name='rivers')
    op.drop_index('idx_rivers_geometry', table_name='rivers', postgresql_using='gist')
    op.drop_table('rivers')
    op.drop_index('ix_rainfall_obs_source_record', table_name='rainfall_observations')
    op.drop_index('ix_rainfall_obs_source_id', table_name='rainfall_observations')
    op.drop_index('ix_rainfall_obs_district_observed', table_name='rainfall_observations')
    op.drop_index('idx_rainfall_obs_geometry', table_name='rainfall_observations', postgresql_using='gist')
    op.drop_table('rainfall_observations')
    op.drop_index('ix_land_covers_source_id', table_name='land_covers')
    op.drop_index('ix_land_covers_district_id', table_name='land_covers')
    op.drop_index('idx_land_covers_geometry', table_name='land_covers', postgresql_using='gist')
    op.drop_table('land_covers')
    op.drop_index('ix_terrain_datasets_source_id', table_name='terrain_datasets')
    op.drop_index('idx_terrain_datasets_coverage', table_name='terrain_datasets', postgresql_using='gist')
    op.drop_table('terrain_datasets')
    op.drop_index('ix_sub_basins_basin_id', table_name='sub_basins')
    op.drop_index('idx_sub_basins_geometry', table_name='sub_basins', postgresql_using='gist')
    op.drop_table('sub_basins')
    op.drop_index('ix_ml_models_dataset_version', table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index('ix_flood_hazard_source_id', table_name='flood_hazard_zones')
    op.drop_index('idx_flood_hazard_geometry', table_name='flood_hazard_zones', postgresql_using='gist')
    op.drop_table('flood_hazard_zones')
    op.drop_index('ix_flood_events_start_time', table_name='flood_events')
    op.drop_index('ix_flood_events_source_id', table_name='flood_events')
    op.drop_index('idx_flood_events_geometry', table_name='flood_events', postgresql_using='gist')
    op.drop_table('flood_events')
    op.drop_index('ix_districts_state_id', table_name='districts')
    op.drop_index('idx_districts_geometry', table_name='districts', postgresql_using='gist')
    op.drop_index('idx_districts_centroid', table_name='districts', postgresql_using='gist')
    op.drop_table('districts')
    op.drop_index('ix_ingestion_runs_started_at', table_name='data_ingestion_runs')
    op.drop_index('ix_ingestion_runs_source_id', table_name='data_ingestion_runs')
    op.drop_table('data_ingestion_runs')
    op.drop_index('ix_community_reports_user_id', table_name='community_reports')
    op.drop_index('ix_community_reports_status', table_name='community_reports')
    op.drop_index('ix_community_reports_reported_at', table_name='community_reports')
    op.drop_index('idx_community_reports_geometry', table_name='community_reports', postgresql_using='gist')
    op.drop_table('community_reports')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index('idx_states_geometry', table_name='states', postgresql_using='gist')
    op.drop_table('states')
    op.drop_index('idx_river_basins_geometry', table_name='river_basins', postgresql_using='gist')
    op.drop_table('river_basins')
    op.drop_table('ml_dataset_versions')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
