"""add hydrological GIS foundation tables and columns

Revision ID: f75e4ffc014c
Revises: ccfc6a6b5d06
Create Date: 2026-09-24 00:22:06.915870
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
import geoalchemy2



# revision identifiers, used by Alembic.
revision: str = 'f75e4ffc014c'
down_revision: Union[str, None] = 'ccfc6a6b5d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_river_basins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('river_basin_id', sa.UUID(), nullable=False),
    sa.Column('intersection_geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('intersection_area_km2', sa.Float(), nullable=True),
    sa.Column('percent_of_basin_in_district', sa.Float(), nullable=True),
    sa.Column('percent_of_district_in_basin', sa.Float(), nullable=True),
    sa.Column('derivation_method', sa.String(length=100), nullable=True),
    sa.Column('source_description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['river_basin_id'], ['river_basins.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'river_basin_id', name='uq_district_river_basin')
    )
    op.create_index('idx_district_river_basins_geom', 'district_river_basins', ['intersection_geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_district_river_basins_district_id', 'district_river_basins', ['district_id'], unique=False)
    op.create_index('ix_district_river_basins_river_basin_id', 'district_river_basins', ['river_basin_id'], unique=False)
    op.create_table('district_sub_basins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('sub_basin_id', sa.UUID(), nullable=False),
    sa.Column('intersection_geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('intersection_area_km2', sa.Float(), nullable=True),
    sa.Column('percent_of_subbasin_in_district', sa.Float(), nullable=True),
    sa.Column('percent_of_district_in_subbasin', sa.Float(), nullable=True),
    sa.Column('derivation_method', sa.String(length=100), nullable=True),
    sa.Column('source_description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['sub_basin_id'], ['sub_basins.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'sub_basin_id', name='uq_district_sub_basin')
    )
    op.create_index('idx_district_sub_basins_geom', 'district_sub_basins', ['intersection_geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_district_sub_basins_district_id', 'district_sub_basins', ['district_id'], unique=False)
    op.create_index('ix_district_sub_basins_sub_basin_id', 'district_sub_basins', ['sub_basin_id'], unique=False)
    op.add_column('river_basins', sa.Column('source_agency', sa.String(length=200), nullable=True))
    op.add_column('river_basins', sa.Column('source_dataset', sa.String(length=200), nullable=True))
    op.add_column('river_basins', sa.Column('source_version', sa.String(length=50), nullable=True))
    op.add_column('river_basins', sa.Column('source_feature_id', sa.String(length=100), nullable=True))
    op.add_column('river_basins', sa.Column('area_km2', sa.Float(), nullable=True))
    op.add_column('river_basins', sa.Column('intersects_karnataka', sa.Boolean(), nullable=True))
    op.add_column('river_basins', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('river_basins', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'river_basins', ['source_feature_id'])
    op.add_column('rivers', sa.Column('hyriv_id', sa.BigInteger(), nullable=True))
    op.add_column('rivers', sa.Column('next_down', sa.BigInteger(), nullable=True))
    op.add_column('rivers', sa.Column('main_riv', sa.BigInteger(), nullable=True))
    op.add_column('rivers', sa.Column('length_km', sa.Float(), nullable=True))
    op.add_column('rivers', sa.Column('dist_dn_km', sa.Float(), nullable=True))
    op.add_column('rivers', sa.Column('dist_up_km', sa.Float(), nullable=True))
    op.add_column('rivers', sa.Column('catch_skm', sa.Float(), nullable=True))
    op.add_column('rivers', sa.Column('upland_skm', sa.Float(), nullable=True))
    op.add_column('rivers', sa.Column('dis_av_cms', sa.Float(), nullable=True))
    op.add_column('rivers', sa.Column('ord_stra', sa.Integer(), nullable=True))
    op.add_column('rivers', sa.Column('ord_clas', sa.Integer(), nullable=True))
    op.add_column('rivers', sa.Column('ord_flow', sa.Integer(), nullable=True))
    op.add_column('rivers', sa.Column('hybas_l12', sa.BigInteger(), nullable=True))
    op.add_column('rivers', sa.Column('source_dataset', sa.String(length=200), nullable=True))
    op.add_column('rivers', sa.Column('source_version', sa.String(length=50), nullable=True))
    op.add_column('rivers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('rivers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('ix_rivers_hyriv_id', 'rivers', ['hyriv_id'], unique=False)
    op.create_unique_constraint(None, 'rivers', ['hyriv_id'])
    op.add_column('sub_basins', sa.Column('hybas_id', sa.BigInteger(), nullable=True))
    op.add_column('sub_basins', sa.Column('next_down', sa.BigInteger(), nullable=True))
    op.add_column('sub_basins', sa.Column('next_sink', sa.BigInteger(), nullable=True))
    op.add_column('sub_basins', sa.Column('main_bas', sa.BigInteger(), nullable=True))
    op.add_column('sub_basins', sa.Column('sub_area', sa.Float(), nullable=True))
    op.add_column('sub_basins', sa.Column('up_area', sa.Float(), nullable=True))
    op.add_column('sub_basins', sa.Column('pfaf_id', sa.BigInteger(), nullable=True))
    op.add_column('sub_basins', sa.Column('endo', sa.Integer(), nullable=True))
    op.add_column('sub_basins', sa.Column('coast', sa.Integer(), nullable=True))
    op.add_column('sub_basins', sa.Column('dist_sink', sa.Float(), nullable=True))
    op.add_column('sub_basins', sa.Column('dist_main', sa.Float(), nullable=True))
    op.add_column('sub_basins', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('sub_basins', sa.Column('sort', sa.BigInteger(), nullable=True))
    op.add_column('sub_basins', sa.Column('source_dataset', sa.String(length=200), nullable=True))
    op.add_column('sub_basins', sa.Column('source_version', sa.String(length=50), nullable=True))
    op.add_column('sub_basins', sa.Column('geometry_repaired', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sub_basins', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('sub_basins', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('sub_basins', 'basin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_sub_basins_hybas_id', 'sub_basins', ['hybas_id'], unique=False)
    op.create_unique_constraint(None, 'sub_basins', ['hybas_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_basins', type_='unique')
    op.drop_index('ix_sub_basins_hybas_id', table_name='sub_basins')
    op.alter_column('sub_basins', 'basin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sub_basins', 'updated_at')
    op.drop_column('sub_basins', 'created_at')
    op.drop_column('sub_basins', 'geometry_repaired')
    op.drop_column('sub_basins', 'source_version')
    op.drop_column('sub_basins', 'source_dataset')
    op.drop_column('sub_basins', 'sort')
    op.drop_column('sub_basins', 'order')
    op.drop_column('sub_basins', 'dist_main')
    op.drop_column('sub_basins', 'dist_sink')
    op.drop_column('sub_basins', 'coast')
    op.drop_column('sub_basins', 'endo')
    op.drop_column('sub_basins', 'pfaf_id')
    op.drop_column('sub_basins', 'up_area')
    op.drop_column('sub_basins', 'sub_area')
    op.drop_column('sub_basins', 'main_bas')
    op.drop_column('sub_basins', 'next_sink')
    op.drop_column('sub_basins', 'next_down')
    op.drop_column('sub_basins', 'hybas_id')
    op.drop_constraint(None, 'rivers', type_='unique')
    op.drop_index('ix_rivers_hyriv_id', table_name='rivers')
    op.drop_column('rivers', 'updated_at')
    op.drop_column('rivers', 'created_at')
    op.drop_column('rivers', 'source_version')
    op.drop_column('rivers', 'source_dataset')
    op.drop_column('rivers', 'hybas_l12')
    op.drop_column('rivers', 'ord_flow')
    op.drop_column('rivers', 'ord_clas')
    op.drop_column('rivers', 'ord_stra')
    op.drop_column('rivers', 'dis_av_cms')
    op.drop_column('rivers', 'upland_skm')
    op.drop_column('rivers', 'catch_skm')
    op.drop_column('rivers', 'dist_up_km')
    op.drop_column('rivers', 'dist_dn_km')
    op.drop_column('rivers', 'length_km')
    op.drop_column('rivers', 'main_riv')
    op.drop_column('rivers', 'next_down')
    op.drop_column('rivers', 'hyriv_id')
    op.drop_constraint(None, 'river_basins', type_='unique')
    op.drop_column('river_basins', 'updated_at')
    op.drop_column('river_basins', 'created_at')
    op.drop_column('river_basins', 'intersects_karnataka')
    op.drop_column('river_basins', 'area_km2')
    op.drop_column('river_basins', 'source_feature_id')
    op.drop_column('river_basins', 'source_version')
    op.drop_column('river_basins', 'source_dataset')
    op.drop_column('river_basins', 'source_agency')
    op.drop_index('ix_district_sub_basins_sub_basin_id', table_name='district_sub_basins')
    op.drop_index('ix_district_sub_basins_district_id', table_name='district_sub_basins')
    op.drop_index('idx_district_sub_basins_geom', table_name='district_sub_basins', postgresql_using='gist')
    op.drop_table('district_sub_basins')
    op.drop_index('ix_district_river_basins_river_basin_id', table_name='district_river_basins')
    op.drop_index('ix_district_river_basins_district_id', table_name='district_river_basins')
    op.drop_index('idx_district_river_basins_geom', table_name='district_river_basins', postgresql_using='gist')
    op.drop_table('district_river_basins')
    # ### end Alembic commands ###
